### PR TITLE
DAC (Digital to Analog Converter) library

### PR DESCRIPTION
**Pull request by brunofalmeida**

### CODE REVIEW

**Comment by brunofalmeida** [comment]
@siddMahen This is now tested and working. I need to do a bit of cleanup but otherwise it's ready to merge.

**Comment by brunofalmeida** [comment]
I'll take a look at these again tomorrow. The LDAC is an optional pin used to update both outputs simultaneously but we don't use it.

**Comment by siddMahen** [comment]
@brunofalmeida todos I see:

- [ ]  test resets
- [ ]  use generic port commands instead of SPI 
- [ ]  power down/up DAC A/B?

**Comment by brunofalmeida** [comment]
Testing the reset should be done now. The other two are debatable for functionality so they are future suggestions.

**Comment by brunofalmeida** [comment]
Just need to run the test

**Comment by brunofalmeida** [comment]
@siddMahen This is tested and working

**Comment by siddMahen** [comment]
Great, will rebase on master and merge.

**Pull request merged**
