### PR TITLE
Add assert library so queue and stack can be properly tested

### PR DESCRIPTION
**Pull request by brunofalmeida**

### CODE REVIEW

**Comment by siddMahen** [comment]
In general, it's not a good idea to merge `master` into branches; you should be merging other branches into master. The way you do this is by *rebasing on top of `master`*. Check out https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by brunofalmeida** [comment]
Yeah sorry about that

**Comment by siddMahen** [comment]
Here's a really good guide to the difference between rebasing and merging, and when you should use what: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by brunofalmeida** [comment]
So in our case, should we just use rebase when integrating commits from master into a feature branch? Are there any other use cases?

**Comment by siddMahen** [comment]
Yes, for the most part. You'd never rebase a branch onto master because rebasing re-writes your commit history, and rewrites the git log, which is annoying for other people who've created branches or want a consistent git history. However, using it on feature branches prevents the creation of multiple, confusing, merge commits. Rebase also provides a powerful feature which allows you to clean up branches before they're merged; I often use `git rebase --interactive` to meld similar commits together, rewrite log messages, etc.

**Pull request merged**
