### PR TITLE
PAY conversions

### PR DESCRIPTION
**Pull request by brunofalmeida**
Add raw data conversion functions for PAY environmental sensors (temperature, humidity, pressure) and the PAY-Optical ADC.

### CODE REVIEW

**Comment by brunofalmeida** [comment]
This is tested and working.

**Comment by siddMahen** [comment]
LGTM; rebased on top of master and consolidated commits. Will merge by tonight unless anyone else wants anything changed.

**Comment by brunofalmeida** [comment]
That makes sense, I updated the documentation and datasheet references. To clarify pressure data, the raw data has one bit representing 0.01 mbar.

**Comment by siddMahen** [comment]
@auderian @brunofalmeida is this ready to merge?

**Comment by auderian** [comment]
@siddMahen just reviewed Bruno's latest changes, looks good to me

**Comment by brunofalmeida** [comment]
Yes it's ready

**Pull request merged**
