### PR TITLE
Queue + stack testing

### PR DESCRIPTION
**Pull request by siddMahen**
I'm creating this pull request early so that those who are interested can see how I work within the git system. This is a mirror of `queue-stack-assert` branch on my local machine. Normally, I would only push to github once I had cleaned up all my commits, rebased etc.

### CODE REVIEW

**Comment by siddMahen** [comment]
I think this is ready for review @brunofalmeida @dhanyaa97 ; tested it on the boards and it runs fine. All that's left is cleaning up the commit history, which I can finish by tonight.

**Comment by brunofalmeida** [comment]
The tests look good to me, but I'm wondering why functions such as `enqueue` return 1 for failure instead of 1 for success?

**Comment by siddMahen** [comment]
The convention to return 1 for failure comes from C systems programming, where when returning from `main()`, 0 means success and non-zero indicated failure and a specific failure code. However, I think you're right; functions like enqueue should return 0 for failure and 1 for success. This can be interpreted as the number of items enqueued, which makes sense, and it also allows you to write code like this:

```
if (!enqueue(&queue, data)) {
   // do something
}
```

which makes a lot of sense to me, and is better than the non `!` alternative.

**Comment by siddMahen** [comment]
Will merge tonight unless anyone has any more comments.

**Comment by brunofalmeida** [comment]
@siddMahen are the tests updated for the new return values?

**Comment by siddMahen** [comment]
@brunofalmeida Yes; I tested one final time after the rebase.

**Pull request merged**
