### PR TITLE
Queue library update

### PR DESCRIPTION
**Pull request by siddMahen**
Accidentally deleted the old branch; sorry!

### CODE REVIEW

**Comment by brunofalmeida** [comment]
Can you consider making `MAX_QUEUE_SIZE` and `MAX_STACK_SIZE` smaller? A single stack or queue currently takes up 400 bytes of the 2KB on the 32M1.

**Comment by siddMahen** [comment]
@brunofalmeida How small do you think we should go? 25?

**Comment by brunofalmeida** [comment]
I would recommend around 10

**Comment by brunofalmeida** [comment]
Maybe up to 20 if you think we need that much space?

**Comment by siddMahen** [comment]
Let's try 10 for now and see how that goes. It seems a little low to me, but I think it's worth the additional strings we can print with.

**Comment by brunofalmeida** [comment]
I would also suggest that `enstack` and `destack` be renamed to `stack_push` and `stack_pop`.

**Comment by siddMahen** [comment]
@brunofalmeida Maybe just `push` and `pop`?

**Comment by siddMahen** [comment]
If someone could review these changes and test this code in lab, I think we're ready to merge.

**Comment by brunofalmeida** [comment]
This still needs to be tested!!!

**Comment by brunofalmeida** [comment]
@siddMahen How is this supposed to be tested? Is it just by running the examples?

**Comment by brunofalmeida** [comment]
This got messed up when I merged `master` into `queue-fix` and resolved conflicts. I reverted the commit of this code on `master` so we can check if the new libraries work, but will probably need to revert the revert.

**Comment by siddMahen** [comment]
@brunofalmeida When you're working with multiple branches, `git pull` isn't always the best idea; its better to use a combination of `git fetch` and `git rebase`. This is slightly more complex, but its worth learning to prevent issues like this in the future.

**Comment by brunofalmeida** [comment]
Alright, I'll take a look at it

**Pull request merged**
