### PR TITLE
Test harness and libtest

### PR DESCRIPTION
**Pull request by siddMahen**
To see this in action, connect a 32m1 with UART RX pin connected to the programmer. This requires Python v2.6+. **WARNING** Make sure the UART TX pin is not connected. Programming the 32m1 with the TX pin connected can cause fuse bits to reset.

Now, run

```
$ python harness.py -p <32m1 port> -d tests/
```

When prompted to start, do not type `y` right away; connect the UART TX pin, and then proceed.

You should see output like:

```
Start? (y/n) y
TEST NAME: Print a string literal
The quick brown fox jumped over the lazy dog.
DONE
TEST NAME: Print w/ formatting
0 1 2 3 4 5 6 7 8 9
DONE
TEST NAME: Print w/ fancy formatting
0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0x09 0x0a 0x0b 0x0c 0x0d 0x0e 0x0f
DONE
```

### CODE REVIEW

**Comment by siddMahen** [comment]
Of course, the point of this testing framework is to test things automatically; we shouldn't have to inspect the output ourselves.

One way to automate the testing is to have an `assert`-like function, with signature, say, `(void)(*assert)(void* t1, void* t2, ...) where the ellipses hide formatted message arguments. So a call to `assert` would look like

```
int main(void) {
    // . . .
    assert_eq(&foo, &bar, "foo != bar, %s != %s", foo, bar);
    // . . .
}
```

Instead of actually asserting anything, this call would sent an `ASSERT EQ foo_contents bar_contents` message to the UART client.

**Comment by siddMahen** [comment]
@brunofalmeida @bonnieweng1T9 Let me know what you think of the assert framework, specifically, look at the tests/arithmetic directory for a toy example of how assertions are used.

**Comment by brunofalmeida** [comment]
1) Can there be a more generic `assert()` or `assert_true()` function that just asserts whether a single parameter is true? We aren't always comparing whether two things are equal, and it might be tedious to use `assert_eq(condition, true)`.

2) Is there a way (or a planned way) to print line numbers or where a particular assert failed? Or will the harness automatically print the name of the test that failed?

3) You noted in `src/test/assert.c` that `assert_eq()` fails with `uint32_t` values. I think the reason is that you need to use `%lu` instead of `%d` in `print()` for 32 bit values.

**Comment by siddMahen** [comment]
1. Yes, that's a very common use case, something like `assert_true()` seems like a good fit.
2. I was thinking of only printing the names of the failed tests, but I think we should copy your assert impl and also add in line numbers via `__LINE__`. I wonder if there's a way to get the name of the function that's currently in scope...
3. Ah! Thank you! That spooked me.

**Comment by siddMahen** [comment]
Examples of current output below. Let me know if wording/aesthetics is nice, happy to incorporate changes.

```
WARNING: The UART TX pin on SCK must be disconnected before upload.
Ensure the UART TX pin is disconnected before proceeding.
Execute test suite 'print'? (y/n) y
    Compiling...
    Linking...
    Uploading...
Connect the UART TX pin to SCK. (ok) ok
--------------------------------------------------------------------------------
Test: Print a string literal
The quick brown fox jumped over the lazy dog.
Test complete
--------------------------------------------------------------------------------
Test: Print w/ formatting
0 1 2 3 4 5 6 7 8 9
Test complete
--------------------------------------------------------------------------------
Test: Print w/ fancy formatting
0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0x09 0x0a 0x0b 0x0c 0x0d 0x0e 0x0f
Test complete
--------------------------------------------------------------------------------
Test: Print debug info
debug_test 23
Test complete
--------------------------------------------------------------------------------
Test suite 'print' complete
    Time elapsed: 0.389 s
    Passed: 0 / 0
    Failed: 0 / 0
--------------------------------------------------------------------------------
WARNING: The UART TX pin on SCK must be disconnected before upload.
Ensure the UART TX pin is disconnected before proceeding.
Execute test suite 'arithmetic'? (y/n) y
    Compiling...
    Linking...
    Uploading...
Connect the UART TX pin to SCK. (ok) ok
--------------------------------------------------------------------------------
Test: Add 1 and 1
In function 'addition_test', line 5
    Error: ASSERT_EQ failed
Test complete
--------------------------------------------------------------------------------
Test: Assert true
In function 'zero_test', line 9
    Error: ASSERT_TRUE failed
Test complete
--------------------------------------------------------------------------------
Test suite 'arithmetic' complete
    Time elapsed: 0.158 s
    Passed: 0 / 2
    Failed: 2 / 2
--------------------------------------------------------------------------------
Summary:
    Total passed 0 / 2
    Total failed 2 / 2
```

**Comment by siddMahen** [comment]
Future directions/features:

* Add support for multi-board tests; this would allow us to test CAN/UART/heartbeat effectively. Multi-board tests would have several sources files, `main1.c`,  `main2.c` etc. This would require an additional struct, perhaps `test_suite_t`, which would provide information on how to many boards were involved in the test, and how to identify them, perhaps using some kind of id, pre-pended to each command, e.g. `1 START\r\n` sends the start command to 1.

* Add support for some kind of timed ASSERT; an assertion that fails unless the test completes in a given amount of time. This could be implemented as another attribute of the `test_t` struct, e.g. a `timeout` attribute. This could be used to test the timer functionality.

Any suggestions, further ideas are welcome.

**Comment by brunofalmeida** [comment]
1) Where it says `Passed:` and `Failed:`, I get the impression that it's talking about the number of tests passed/failed, rather than it actually being the number of asserts passed/failed.

2) Maybe the section labelled `Summary:` should indicate that it's the summary of all test suites? It might imply that it's the summary of a single test suite if you're only reading the output from the last test suite.

I don't think either of these points are a huge deal, just my first impressions when reading the output.

**Comment by siddMahen** [comment]
@brunofalmeida @timmysilv @BrytniR @jackberezny @alihaydaroglu Would like to merge this by tomorrow evening, please take a look and let me know if anything needs fixing.

**Comment by siddMahen** [comment]
Example of current output:

```
$ python ./bin/harness.py -p /dev/tty.usbmodem00208212 -d tests
Skipping test suite 'multi-board', requires 1 more board(s).
WARNING: The UART TX pin(s) on SCK must be disconnected before upload.
Ensure the UART TX pin on each board is disconnected before proceeding.
Execute test suite 'print'? (y/n) n
WARNING: The UART TX pin(s) on SCK must be disconnected before upload.
Ensure the UART TX pin on each board is disconnected before proceeding.
Execute test suite 'arithmetic'? (y/n) y
    Compiling...
    Linking...
    Uploading...
Connect the UART TX pin(s) to SCK. (ok) ok
--------------------------------------------------------------------------------
Test: Add 1 and 1
In function 'addition_test', line 8
    Error: ASSERT_EQ failed
Test complete
--------------------------------------------------------------------------------
Test: Assert true
Test complete
--------------------------------------------------------------------------------
Test: 100 ms
    Error: expected test to complete in 0.10 s, took 0.21 s
Test complete
--------------------------------------------------------------------------------
Test suite 'arithmetic' complete
    Time elapsed: 0.431 s
    Passed: 1 / 3
    Failed: 2 / 3
--------------------------------------------------------------------------------
Summary:
    Total passed 1 / 3
    Total failed 2 / 3
```

**Comment by siddMahen** [comment]
@brunofalmeida Maybe `Passed` and `Failed` should reflect the number of tests passes/failed, instead of number of assertions passed/failed. The rationale being if an early assertion fails, most future assertions are also going to fail. All failing assertions can still be listed as errors.

**Comment by brunofalmeida** [comment]
Maybe where it says `Test complete` it should say whether that test passed or failed?

**Comment by siddMahen** [comment]
Ok, so from now on, `Passed` and `Failed` reflect the number of tests that have passed/failed.

**Comment by bonnieWeng** [comment]
Please correct me if I have any poor understanding in your current awesome test harness framework. Is the current framework checking the print statements?! rather than register values on 32M1?! Asking cuz for heartbeat, it will be great if assert test is to assert the contents in EEPROM memory.

**Comment by bonnieWeng** [comment]
As for feedback for the current framework, this is great, @siddMahen! Thanks for your hard work! I also think we can turn this framework into how we can show our functionality for qual.?! @brunofalmeida Thoughts? Perhaps, once test harness is merged and some portion of the SSM program is done, someone can start drafting the qual testing files.

**Comment by siddMahen** [comment]
@bonnieWeng The current framework is not checking 32m1 register values; this turned out to be more complicated than I thought. Instead, it asks the UART client (in this case, the harness) to perform assertions on its behalf.

This might not be directly useful for qual, but at the least it'll be very similar. For qual, I'm imagining a UART-based system where we can send OBC commands and have it respond appropriately. I'm going to begin working on that soon.

**Comment by siddMahen** [comment]
Latest example output:

```
$ python ./bin/harness.py -p /dev/tty.usbmodem00208212 -d tests
Skipping test suite 'multi-board', requires 1 more board(s).
WARNING: The UART TX pin(s) on SCK must be disconnected before upload.
Ensure the UART TX pin on each board is disconnected before proceeding.
Run test suite 'print'? (y/n) y
    Compiling...
    Linking...
    Uploading...
Connect the UART TX pin(s) to SCK. (ok) ok
--------------------------------------------------------------------------------
Test: Print a string literal
The quick brown fox jumped over the lazy dog.
Test complete - Passed
--------------------------------------------------------------------------------
Test: Print w/ formatting
0 1 2 3 4 5 6 7 8 9
Test complete - Passed
--------------------------------------------------------------------------------
Test: Print w/ fancy formatting
0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0x09 0x0a 0x0b 0x0c 0x0d 0x0e 0x0f
Test complete - Passed
--------------------------------------------------------------------------------
Test: Print debug info
debug_test 23
Test complete - Passed
--------------------------------------------------------------------------------
Test suite 'print' complete
    Time elapsed: 0.439 s
    Passed: 4 / 4
    Failed: 0 / 4
--------------------------------------------------------------------------------
WARNING: The UART TX pin(s) on SCK must be disconnected before upload.
Ensure the UART TX pin on each board is disconnected before proceeding.
Run test suite 'arithmetic'? (y/n) y
    Compiling...
    Linking...
    Uploading...
Connect the UART TX pin(s) to SCK. (ok) ok
--------------------------------------------------------------------------------
Test: Add 1 and 1
In function 'addition_test', line 8
    Error: ASSERT_EQ failed
Test complete - Failed
--------------------------------------------------------------------------------
Test: Assert true
Test complete - Passed
--------------------------------------------------------------------------------
Test: 100 ms
    Error: expected test to complete in 0.100 s, took 0.205 s
Test complete - Failed
--------------------------------------------------------------------------------
Test suite 'arithmetic' complete
    Time elapsed: 0.431 s
    Passed: 1 / 3
    Failed: 2 / 3
--------------------------------------------------------------------------------
Testing summary:
    Total passed: 5 / 7
    Total failed: 2 / 7
```

**Comment by siddMahen** [comment]
@bonnieWeng @brunofalmeida Also, I would like tests to be written for this framework before/concurrently with the OBC-based qual tests.

**Comment by siddMahen** [comment]
@brunofalmeida @bonnieWeng @alihaydaroglu as per Github's new rules, I can't merge this pull request until it has been approved by at least one other person. Does anyone mind taking a look?

**Comment by brunofalmeida** [comment]
I thought you could leave an approving review yourself since you have write access?

**Pull request merged**
