### PR TITLE
Utilities library

### PR DESCRIPTION
**Pull request by brunofalmeida**
It would be useful to have a utilities library of miscellaneous common operations. We could add more functionality later, but it currently has:

- A function for printing an array of `uint8_t` bytes in hex format
- Defines the `F_CPU` macro for `<util/delay.h>` once so it doesn't need to be redefined in every file we use delays

### CODE REVIEW

**Comment by siddMahen** [comment]
Since this always requires UART to be active, I think we should just add it to the UART library as it's own function.

**Comment by siddMahen** [comment]
For the time being, I think we can do without a utilities library; the print hex function is useful, and although it is slightly annoying to write out the value of F_CPU each time, the compiler reminds you, so nothing breaks if you forget.

**Comment by brunofalmeida** [comment]
- I think it would be a problem if someone defines F_CPU as the wrong value when rewriting it, might be good to have a standard constant value
- How would you test that UART actually printed the right string and that the delay is for the right amount of time?

**Comment by siddMahen** [comment]
@brunofalmeida As an external program, the test harness can test both delays and UART output, so testing is not an issue. See the `time` parameter in the `test_t` struct in `test.h` and the associated commit message for timing-based test info, as well as the `arithmetic` test, which includes a delay test. Testing UART output would be easier with a new `ASSERT_STR` macro, but that isn't too difficult to add; I'll make a note of it.

I agree that it would be problematic if someone defined F_CPU incorrectly, but I think that the cost of hauling around another library isn't worth it.

**Comment by brunofalmeida** [comment]
Ok that makes sense. I'd still like to add `print_hex_bytes()` to the UART library though.

**Comment by siddMahen** [comment]
@brunofalmeida @dhanyaa97 See #54

**Pull request closed without merging**
