### PR TITLE
Rewrite queue library

### PR DESCRIPTION
**Pull request by siddMahen**
* Implements FIFO queue without heap allocation
* Conforms to lib-common style
* Minor makefile fixes
* Created queue example

### CODE REVIEW

**Comment by siddMahen** [comment]
@shimismith @vogeldylan please review

**Comment by siddMahen** [comment]
This still needs to be tested on boards, if anyone does this, please post results here.

**Comment by siddMahen** [comment]
Tested this in lab; seems to work. Will merge soon unless anyone has anything else to add.

**Comment by vogeldylan** [comment]
Looks fine to me!

**Pull request merged**
