### PR TITLE
Timer improvements

### PR DESCRIPTION
**Pull request by brunofalmeida**

### CODE REVIEW

**Comment by brunofalmeida** [comment]
@siddMahen how is this for style?

**Comment by siddMahen** [comment]
Are both timers necessary? @BrytniR @timmysilv

**Comment by timmysilv** [comment]
@siddMahen with the limited amount of thought we put into it, we decided an easy way to add a second timed function is by adding a second timer. There isn't really the pure h/w benefit because the timer code Shimi made uses s/w as well, so we could just make different commands occur periodically based on one timer in s/w. Totally up for discussion but hey now we have 2.

**Comment by siddMahen** [comment]
@timmysilv ah, so just to clarify, there's one hardware timer driving two software timers?

**Comment by siddMahen** [comment]
Also, this branch **cannot** be merged until its git history is cleaned up using `git rebase`.

**Comment by timmysilv** [comment]
@siddMahen they're actually 2 separate hw timers with periods too small for us to use, so we manage both by essentially using their max periods a certain number of times, which is done in software. Virtually identical except one's 16-bit, and the other is 8-bit

**Comment by siddMahen** [comment]
Ah ok, thanks. Maybe we should rename them timer_8t and timer_16t, to denote which hardware timer the software timers are based on?

**Comment by siddMahen** [comment]
@BrytniR Is there a reason `set_vars_` is public? Is there a mechanism to turn timers on and off?

**Comment by timmysilv** [comment]
@siddMahen no, it can be made private.

**Comment by siddMahen** [comment]
@BrytniR @brunofalmeida @timmysilv Just rebased on top of master; this should be ready to merge. Could someone quickly review this?

**Pull request merged**
